# Generated by Django 3.2.15 on 2022-09-12 15:19

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simulator.models
import simulator.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('type', models.CharField(choices=[('sas', 'Stand Alone Storage'), ('pvs', 'PV + Storage'), ('ws', 'Wind + Storage'), ('ma', 'Mobility Applications')], default='sas', max_length=100)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(blank=True, null=True, upload_to=simulator.models.simulation_directory_path, validators=[simulator.validators.validate_file_extension])),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_files', to='simulator.simulation')),
            ],
        ),
    ]
