# Generated by Django 3.2.15 on 2022-09-14 12:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_alter_simulationinput_simulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='end',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='start',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='title',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='type',
            field=models.CharField(blank=True, choices=[('sas', 'Stand Alone Storage'), ('pvs', 'PV + Storage'), ('ws', 'Wind + Storage'), ('ma', 'Mobility Applications')], default='sas', max_length=100),
        ),
    ]
