# Generated by Django 3.2.15 on 2022-08-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_auto_20220817_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
