# Generated by Django 3.2.15 on 2022-08-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_alter_composite_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composite',
            name='base_elements',
            field=models.ManyToManyField(blank=True, to='simulator.BaseElement'),
        ),
    ]
