# Generated by Django 3.2.15 on 2022-08-17 10:49

from django.db import migrations, models
import simulator.validators


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_auto_20220817_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='input_file',
            field=models.FileField(null=True, upload_to='inputs/', validators=[simulator.validators.validate_file_extension]),
        ),
    ]
