# Generated by Django 3.2.15 on 2022-09-14 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_auto_20220914_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulation',
            old_name='description',
            new_name='project_description',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='title',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='type',
        ),
        migrations.AddField(
            model_name='simulation',
            name='project_type',
            field=models.CharField(blank=True, choices=[('Stand Alone Storage', 'Stand Alone Storage'), ('PV + Storage', 'PV + Storage'), ('Wind + Storage', 'Wind + Storage'), ('Mobility Applications', 'Mobility Applications')], default='Stand Alone Storage', max_length=100),
        ),
        migrations.AlterField(
            model_name='simulationinput',
            name='simulation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulation_input', related_query_name='simulation_input', to='simulator.simulation'),
        ),
    ]
