# Generated by Django 3.2.15 on 2022-09-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0004_auto_20220914_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
