services:
  db:
    image: postgres
    restart: always
    container_name: db_${APP_CODE}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

  web:
    build: ./web
    command: python3 manage.py runserver 0.0.0.0:8000
    container_name: web_${APP_CODE}
    volumes:
      - ./web:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
