networks:
    aza-net:
      
services:
  db:
    image: postgres
    restart: always
    container_name: db_${APP_CODE}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - aza-net

  web:
    build: ./web
    command: python3 manage.py runserver 0.0.0.0:8000
    container_name: web_${APP_CODE}
    volumes:
      - ./web:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - aza-net

  redis:
    image: "redis:alpine"
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - aza-net
